google_page_speed_api: #page speed api
crawl_files:
    - 'meta_keywords_multiple.csv'
    - 'meta_description_over_940_pixels.csv'
    - 'meta_keywords_duplicate.csv'
    - 'meta_description_over_155_characters.csv'
    - 'meta_description_below_70_characters.csv'
    - 'meta_keywords_missing.csv'
    - 'meta_description_multiple.csv'
    - 'meta_description_below_400_pixels.csv'
    - 'meta_description_duplicate.csv'
    - 'meta_description_missing.csv'
    - 'page_titles_missing.csv'
    - 'page_titles_below_30_characters.csv'
    - 'page_titles_over_65_characters.csv' 
    - 'page_titles_multiple.csv'
    - 'page_titles_below_200_pixels.csv'
    - 'page_titles_duplicate.csv'
    - 'page_titles_over_568_pixels.csv'
    - 'page_titles_same_as_h1.csv' 
    - 'external_javascript.csv'
    - 'external_images.csv'
    - 'external_flash.csv'
    - 'external_pdf.csv'
    - 'external_css.csv'
    - 'external_other.csv'
    - 'external_html.csv'
    - 'external_unknown.csv'
    - 'internal_html.csv'
    - 'internal_pdf.csv'
    - 'internal_other.csv'
    - 'internal_unknown.csv'
    - 'internal_images.csv'
    - 'internal_flash.csv'
    - 'internal_css.csv'
    - 'internal_javascript.csv'
    - 'h1_missing.csv'
    - 'h1_over_70_characters.csv'
    - 'h1_multiple.csv'
    - 'h1_duplicate.csv'
    - 'h2_missing.csv'
    - 'h2_duplicate.csv'
    - 'h2_over_70_characters.csv'
    - 'h2_multiple.csv'
    - 'url_underscores.csv'
    - 'url_non_ascii_characters.csv'
    - 'url_over_115_characters.csv'
    - 'url_duplicate.csv'
    - 'url_uppercase.csv'
    - 'url_parameters.csv'
    - 'protocol_http.csv'
    - 'response_codes_no_response.csv'
    - 'response_codes_redirection_(3xx).csv'
    - 'response_codes_blocked_resource.csv'
    - 'response_codes_blocked_by_robots_txt.csv'
    - 'response_codes_server_error_(5xx).csv'
    - 'response_codes_client_error_(4xx).csv'
    - 'response_codes_redirection_(meta_refresh).csv'
    - 'response_codes_redirection_(javascript).csv'